// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjQR1sWDECxX7MwF8R_E_4hs5i1bWBYM',
    appId: '1:715444484117:web:12fbf112872dd93901b61c',
    messagingSenderId: '715444484117',
    projectId: 'moblieapp-c84dc',
    authDomain: 'moblieapp-c84dc.firebaseapp.com',
    storageBucket: 'moblieapp-c84dc.firebasestorage.app',
    measurementId: 'G-5B9W3CX5J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLx2UPbvxtsB6sgeKb8g-4-mfbC56eME',
    appId: '1:715444484117:android:63e5dcac4b6a02b901b61c',
    messagingSenderId: '715444484117',
    projectId: 'moblieapp-c84dc',
    storageBucket: 'moblieapp-c84dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJzpDVJcNy2Td8F2aazr5MUyK0F5jaSso',
    appId: '1:715444484117:ios:142cbadb4bf88a7001b61c',
    messagingSenderId: '715444484117',
    projectId: 'moblieapp-c84dc',
    storageBucket: 'moblieapp-c84dc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJzpDVJcNy2Td8F2aazr5MUyK0F5jaSso',
    appId: '1:715444484117:ios:142cbadb4bf88a7001b61c',
    messagingSenderId: '715444484117',
    projectId: 'moblieapp-c84dc',
    storageBucket: 'moblieapp-c84dc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpjQR1sWDECxX7MwF8R_E_4hs5i1bWBYM',
    appId: '1:715444484117:web:8ebb6099868d17cc01b61c',
    messagingSenderId: '715444484117',
    projectId: 'moblieapp-c84dc',
    authDomain: 'moblieapp-c84dc.firebaseapp.com',
    storageBucket: 'moblieapp-c84dc.firebasestorage.app',
    measurementId: 'G-HGS9KB3BSQ',
  );
}
